name: mg_sub
description: A lightweight reactive controller architecture with GetIt and RxDart.
version: 1.1.1
license: MIT
homepage: https://github.com/mohamadalghanem474/mg_sub
repository: https://github.com/mohamadalghanem474/mg_sub
issue_tracker: https://github.com/mohamadalghanem474/mg_sub/issues
documentation: https://github.com/mohamadalghanem474/mg_sub

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  rxdart: ^0.28.0

dev_dependencies:
  build_runner: ^2.9.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

flutter: null
